name: Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 18.x

      - run: yarn --immutable
        name: Install dependencies

      - run: yarn build
        name: Build site

      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy to Github Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
